name: Telegram test

on:
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install requests
        run: pip install requests

      - name: Run bot
        run: |
          pwd
          ls -la
          python hh_parser.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
